name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test -v ./...

    - name: Build examples
      run: |
        go build -v ./examples/basic
        go build -v ./examples/connectors
        go build -v ./examples/planning

    - name: Extract release notes
      id: extract_notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract_notes.outputs.version }}
        body: |
          ## What's New in ${{ steps.extract_notes.outputs.version }}

          See [CHANGELOG.md](https://github.com/getaxonflow/axonflow-go/blob/main/CHANGELOG.md) for details.

          ## Installation

          ```bash
          go get github.com/getaxonflow/axonflow-go@${{ steps.extract_notes.outputs.version }}
          ```

          ## Documentation

          - [Go Package Documentation](https://pkg.go.dev/github.com/getaxonflow/axonflow-go@${{ steps.extract_notes.outputs.version }})
          - [README](https://github.com/getaxonflow/axonflow-go#readme)
          - [Examples](https://github.com/getaxonflow/axonflow-go/tree/main/examples)

        draft: false
        prerelease: false

  notify:
    name: Notify pkg.go.dev
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Trigger pkg.go.dev update
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        curl https://proxy.golang.org/github.com/getaxonflow/axonflow-go/@v/$VERSION.info
